spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9000
  servlet:
    context-path: /auth
auth:
  salt: VLXMGMAUTHDEV
  sign: Velox
  sessionTime: 3600000
token:
  forgot-password:
    expired-in-minutes: 30
  seller-user-registration:
    expired-in-minutes: 4320
  bidder-user-registration:
    expired-in-minutes: 4320
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/local
    username: local
    password: local

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://development.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/development
    username: development
    password: BaR#!09Nes$$!Ca

---
spring:
  profiles: e2etest
  datasource:
    url: jdbc:mysql://e2etest.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/e2etest
    username: e2etest
    password: bCYmTXwb34yVzjZT

---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://staging.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/staging
    username: staging
    password: Tr1s%TarI$!!80

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://production.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/production
    username: velox
    password: velox_db_2016
