spring:
  datasource:
    url: jdbc:mysql://localhost/local?autoReconnect=true&useSSL=false
    username: local
    password: local
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true

server:
  port: 8081
  servlet:
    context-path: /auth

auth:
  salt: VLXMGMAUTHDEV
  sign: Velox
  tokenTime: 3600000