spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9000
  servlet:
    context-path: /auth
auth:
  salt: VLXMGMAUTHDEV
  sign: Velox
  sessionTime: 3600000
token:
  forgot-password:
    expired-in-minutes: 30
  seller-user-registration:
    expired-in-minutes: 4320
  bidder-user-registration:
    expired-in-minutes: 4320
mail:
  from: Velotrade [noreply address] <noreply@velotrade.com>
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/local
    username: local
    password: local
server:
  web: http://local.velotrade.tech/

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://development.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/development
    username: velotrade
    password: 3T8zszUcXpHWUK7k
server:
  web: https://development.velotrade.tech/

---
spring:
  profiles: e2etest
  datasource:
    url: jdbc:mysql://e2etest.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/e2etest
    username: e2etest
    password: bCYmTXwb34yVzjZT
server:
  web: https://e2etest.velotrade.tech/

---
spring:
  profiles: staging
  datasource:
    url: jdbc:mysql://staging.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/staging
    username: velotrade
    password: Tr1s%TarI$!!80
server:
  web: https://staging.velotrade.com/

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://production.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/production
    username: velox
    password: velox_db_2016
server:
  web: https://platform.velotrade.com/
