spring:
  datasource:
    url: jdbc:mysql://staging.c0vty0c0gtfb.ap-southeast-1.rds.amazonaws.com/staging
    username: staging
    password: Tr1s%TarI$!!80
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 9000
  servlet:
    context-path: /auth

auth:
  salt: VLXMGMAUTHDEV
  sign: Velox
  sessionTime: 3600000

token:
  forgot-password:
    expired-in-minutes: 30
  seller-user-registration:
    expired-in-minutes: 4320
  bidder-user-registration:
    expired-in-minutes: 4320